#ENC[AES256_GCM,data:sU1SUcb0IPHZ2KPkjR7l1g==,iv:qViB51UrF17h1KKugHgZ5bMdZz9mnyz74LbwLpW9QPQ=,tag:g8V3r9u/UY02prM9fMty+g==,type:comment]
git:
    ssh-key-pub: ENC[AES256_GCM,data:2O6ALH6hG1G3CJk+S8Gq/i0PO3nf3o5QrCdYiK6Q/8xS9B03DJW+YbB8zOn5HfMHWD19SoY/mC3qFKlnzal8gNA7mJnsJCeHJAu+nOe2zQI=,iv:Wo/Tn6xpZ4LGnIAoSy5lbVdlsV2tP4HmQo0TvNEmojI=,tag:2O0QTU86bGNTXvj5XN+CzQ==,type:str]
    ssh-key-priv: ENC[AES256_GCM,data:0/iOmpJFeee0Hoq6jbtbqV10zcjGRv0j612Ns1p2a9XR90OxmPT6XZOM6dQjtLRIAtHZLwaE7Gt9Ti9TYFkcUKtTAU33CjwGwzGMLb7STC0Eyzdxi884vA89MoWsp5PpgflKig==,iv:u4GNtT1iTHreEHEEpf0ZXuu4+nUc6EGd6v8l2U+FSZY=,tag:nVloaJWUMZLr3E8FHY83VQ==,type:str]
    ssh-key: ENC[AES256_GCM,data:2WyCN/fziolAgi3iskxLs/4ERdImzBVgj5XhyBxhRW42IdxijeSPIrBUHJ9jhgYHDW/SYP970AwtqUz7OIsrpVsu9KQisFhuswxrnhQ7/gNeTMlk8winMDugrQqMufURbSJMPdY6BeMnOL86BzLiZkYES4OPAd3iUNtg488kiAI5t5u7hCMrCwWBNY+bRa8uKs4VYhN24loHOg8Z0Qm3vkEN8x7xNP6kwejJRtHKZCAWW8XmMNcnsbapqdM7n1q6MClcg6N+grI1izb306xzfzVPz0C/xf2EkEW0xq+yUvKnpfQ24NSbD8O11ed2t/NDZ8FW10/R1igvvzN6ybdEDo4k+86Le+DmwgZmZhkoUiyE12rRhMMNFN2KVF4ZsR9YXPYRRYmqGi4ljdP2VCea8kZg6vJuuA3ogKZknwoSPue+BoCnbgxg6DE4IyIgTJPzuh3kZTb42lHjfI5abn4q/iJEeo4V7nx473ynjVhcdW7PMdps2WrZtcG6hQMsbAaOWNoA6swrNa3aExE57B96BVK8U13gUfOambX1,iv:zU016S3Mn0Idwk0uYn/sQrL0tWB47tuvwAyIKJiPzv8=,tag:lfqivdtNUseuDyMDjFkjHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zgflvqktlgujsaenam2jpmy96n45cpanxv6rz4gpuwhmw7j6ucvsh55q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YlN5V3BKTVpNK1NhYk04
            MUZoNnN1citQdm1qV1RZanMwRWNXMjNoSVVrCkc0MnhkZUxZcU1NU2pHa01SdTQz
            SEM3THE4dUg0a2MzMGRzdm1OVk0yY1EKLS0tIFM5RTRYSktiWFJHUXdWV1VGWmxN
            L1kvZWhVMDBKNjMzZjZoZDY5d0NHWlEKGxy5BL0fcPQGJM6bektMqtzwiiVD4joY
            l2J3p1wioroLjsK54RqSeaOybwCla8IbuzRMFqo5fjlMQ4FE+bnhcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T13:51:01Z"
    mac: ENC[AES256_GCM,data:T9aIyB29t6mtkcWHlF4szrZvak+Niowc7V6Y/XhvznR4TSwe+dqR5epadOPtihdchG47r+LAzb6T6bw3DSXwYtKNNjdouv6tLvQFFs+cksDbtQjMkS0qKnqe9eyFyxSutbr75BH0OMKt/CwZFFNvOlJKPANIBSvjn6iwGm1q5BI=,iv:OnQcDz0jtnUJM2h/IKxakLLlhb2pavUvkTo9/GKJaSo=,tag:42WpulWvnOXw34Gux3sn9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
