placeholder: ENC[AES256_GCM,data:O/4=,iv:yOH8fxNI4g92ehhiP5WAAv3f1LGGRZhLVEl4hLT2BrA=,tag:lvXoKOY/nxVg7gtLdvqfLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zgflvqktlgujsaenam2jpmy96n45cpanxv6rz4gpuwhmw7j6ucvsh55q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YlN5V3BKTVpNK1NhYk04
            MUZoNnN1citQdm1qV1RZanMwRWNXMjNoSVVrCkc0MnhkZUxZcU1NU2pHa01SdTQz
            SEM3THE4dUg0a2MzMGRzdm1OVk0yY1EKLS0tIFM5RTRYSktiWFJHUXdWV1VGWmxN
            L1kvZWhVMDBKNjMzZjZoZDY5d0NHWlEKGxy5BL0fcPQGJM6bektMqtzwiiVD4joY
            l2J3p1wioroLjsK54RqSeaOybwCla8IbuzRMFqo5fjlMQ4FE+bnhcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T04:43:01Z"
    mac: ENC[AES256_GCM,data:fFnydVkftLsoKb0u5lCqvAJ+WD7nTbIAAjuglqT6vme3Qj16mVlbZYrS6cVJ+TgJX6hX0b1lv11Bh+qsQicX3MYDbNzIwx8dDBNQX9wLSFEW5Hp5GdcYo22U8Oxl8DAhW7px+GsigAi6s2yckIM+TRkOAB83lGtMa76NJM3mn1k=,iv:1aI3heEWRxACPcxEZR7wGtNXiGUyY/EEgITDStL5ow4=,tag:VpuonPVBfb92zosVKYLaWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
