keys:
  - &magnetar age1zgflvqktlgujsaenam2jpmy96n45cpanxv6rz4gpuwhmw7j6ucvsh55q20
creation_rules:
  - path_regex: secrets/shared/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *magnetar
  - path_regex: secrets/magnetar/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *magnetar
