keys:
  # magnetar: Macbook Air M1
  - &user_magnetar_peario age1zgflvqktlgujsaenam2jpmy96n45cpanxv6rz4gpuwhmw7j6ucvsh55q20
creation_rules:
  - path_regex: secrets/magnetar/peario/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_magnetar_peario
  # Any non-system dependant secrets
  - path_regex: secrets/peario/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_magnetar_peario
