cachix:
    cache: ENC[AES256_GCM,data:966kpV9FpoGsZLkGhpc7iUVsT3Aa8ozGkbsuFtUtNClLcRtIw8U6THExFXfnAEj3a3XreI/vuqdqYzqJBVmKz0h5q2wNyKpQ0lj2zftm8kmHwqVdkxf7uINdHnzMWa74850UkntlK/ziWsHVDIt6suHZEp177QdVN0goH91RlQPql/xgXsrNNugo3ecxoU8K1OxpnGQ=,iv:vkx47qIdG8MPiIedpQeuUd+lA9VxJm/YnMLXJIAzNRQ=,tag:Mk710P1wKoq+QJQFqzl7dA==,type:str]
    agent: ENC[AES256_GCM,data:4aTZ27ApJAKKr38wNJYanRRy7UcoAGKzNLTSzgBdKovkazkjALOwZn0wpR2omq9gbe4QpbjD2F2p2WWHcpXaSJa6nQPNzHwpPhpaNMaU+IhdwUlRDbb9JCntuHk2RU1k14Mk3hhd8G36V4f4nCTNFYj/xFIduMoH7EKG0XD94Igr0xFbNfSkV6kz4ZiYxdAPbyQW1qs=,iv:JCwQgigrtH647YO9KobHp3P3cjV5KI7mMAn8zTe/300=,tag:RyuQXM0ySQ7VeMu3a3OXjQ==,type:str]
github:
    access-token: ENC[AES256_GCM,data:RIZSotAoH4TjFmgAlfcSnzvF/PT8Q1GL09kr93AeIg7DCdb/4RnDXA==,iv:7NE7GH1JeJGn1AWYjqitBeX9YeLqyi5WSEcUP+AHXYs=,tag:3tKEa+B5wkgWqy+d7rwhZQ==,type:str]
nix: ENC[AES256_GCM,data:oNTMP0TrN7Jx/soL7EQtYRTkSvulH8/Ghp9cZh8p8r/PwWpFs3UYDw2WTJ+gzNp4fKfu7vzlAaR8C39UKjXTgQePFo+opaOHZa9+VZU7dg6/IxOhQyHtkT/na/tXS0eiZGqKqgIK+LxcM+Q0SMTwL2njOwMx6dG5wWzpVk7zWErhenAMXqjcMkLeJgqz2D0RyPbqXo2EntBBTlzlBMQUwhjycVlt71p3yqeqF62JFOK+SrnwRIoPACrycEhDXVgWmA1I0I42kVyRb1bb4Jy3n1xtjCMTGu+YQuvohWhljuU0whGDjRbWQ7csaZpwt7eXuTSokDPgcg3Of1JAvbkvESn/6rLFCsKoq04tgRGrdAZUNrJxp7yUuuzcyrjlUsN4bl2qWfTIMd1mF3FQGlvzZTXR+oPmLZcb85vNxixqxNTVgshrU4hf6CaMzmALHJ88LQDkxwyGfwtJg3an8IQj5myc5dLyibURdqYbd8q2BaOZ1QlcjQm1gMmg3hKABwSzdaA1Je0QlpXhr85xHM2HCVIXNa12W7BeVxv8BzVlDHp/W6qmfw9QgfTUNdvV2kR89jXwutYBYbC2oyEEzhnTKL1WZY5hmJWNra9E9PbpiHwYfbcdZjCKGJEYtVAWzU8G0uz37dY3w61ACInMGJlQRY1C0rHLk0TNvTPY0dIchuIRoMGKDjr7Eqwxle5ENwQDouTvKWFXR7QHvIjLM8PRpuwxiEA+uNgYUPTo67CRRLUoUWqasxeNnwUMHMVZIKGH/ubDQ3MIgZ8uo7Eb7mxd1XSAFAn6c/ccnqx4np/oRy6wcxBCL9CiQ6HSZ7dwXkYNFRGpjt+XvJFONuGAWXRnCUOShNlm+8rsYy23Q9hn,iv:+DiEowIUIl1S47SftLTHBM/oe2xPByZBQ4NPYs84yf4=,tag:OQLrU7o7nCpi5K0OzIXKyw==,type:str]
wakatime:
    key: ENC[AES256_GCM,data:bRYOniRUwpKujCl75/Q1BqilAUGby7bj2N6599FhOwNXyr580KcYLW0=,iv:FSBsoxg9vpmEW1Z4NhZtwGk1xjl/3SspxD6MO1jiDo8=,tag:HgkjHjgkt9LAo71a+ib25w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zgflvqktlgujsaenam2jpmy96n45cpanxv6rz4gpuwhmw7j6ucvsh55q20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK3ViQVpaMVk3a2R3UlFI
            L29GS1JKRkZCTG5Tc1FYcExBQitraXl5NlRnCnlPLzFFL2pYZ051VCtTNGd0bm1U
            MU9jMTQzaUNsMEtUNXQrMHUzc0tKQzgKLS0tIG5GWDFYVmZtNEZZSnptUkpwMFMr
            MWE3SVN6U3lTR3BGeXA4S3dnZklqQ2sKkk8Xm50NubD04wpxujS0XyBVHpSgUt3m
            q5S9Cd0QiAF0qQKGre+gIHCfIgb7DGS8NerXoRzvx9QbUsr43Snepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T08:05:25Z"
    mac: ENC[AES256_GCM,data:stVHN3mL6koH7HlRxC6Z9Flz4piEUPjjKelC3ROTk0GsRMJ0F+GYuidwn3HDeS8RmWz30qfpv4tN/CfMryuIB9sEE9as2ztPrSZyDiCjZyKLAR9ZdfOUme0To30jhOGyv8taM4Z4akNlQHsdY6r4BpjTVgmg/eXwRm4YwUEOwsQ=,iv:3m9DjYF/vPpMVgCYRGDX14JHo+mZ0Cd+c2fRrpRz7UM=,tag:UObizBbY0WjNyv/lUKcFXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
