name: Dead code analysis

on: [push, workflow_dispatch]

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Set up Cachix for dead code cache
        uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - name: Find and delete dead nix code
        uses: astro/deadnix-action@main
        with:
          commit_message: "chore: Remove dead code"
