name: Formatter

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting:
    name: Format expressions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#nixfmt-rfc-style -- .
