name: Linter

on: [push, workflow_dispatch]

jobs:
  statix:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Set up Cachix for lint cache
        uses: cachix/cachix-action@v15
        with:
          name: statix
      - name: Lint nix code
        uses: jocelynthode/statix-action@master
