name: Updater

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00, see https://crontab.guru/#0_0_*_*_*

jobs:
  update_flakes:
    name: Update flake.lock
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          pr-assignees: peario
          pr-reviewers: peario
